### ISSUE TITLE
Unable to get NewsGuard file

### ISSUE THREAD

**Issue by Gautamshahi** [JanaLasser/new-ontology-of-truth#1]
Hello Jana, 

I can not get the NewsGuard_labels.csv file in the data. Would it be possible to share the rating files for NewsGuard_labels?

**Comment by JanaLasser** [comment]
Hello Gautam,
I cannot share the NewsGuard_labels.csv file since they require obtaining a license from NewsGuard. You can use different ratings to measure news quality, see for example this paper: https://doi.org/10.1093/pnasnexus/pgad286
